# fly.toml app configuration file generated for web-app-template on 2023-10-17T10:20:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "web-app-template"
primary_region = "ord"

[build]

[[mounts]]
  source = "web_app_template_data1"
  destination = "/pb/pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
