name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'web-app-template'
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        # runs "npm i" as well
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      - name: Run tests (development)
        run: npm run test:github

#      - name: Run Frontend Tests (Development)
#        run: npm run test:github frontend

#      - name: Build Frontend (Development)
#        run: npm run build

#      - name: Run e2e Tests (Development)
#        uses: cypress-io/github-action@v5
#        with:
#          install: false
#          start: |
#            npm run backend

#      - name: Install Flyctl
#        uses: superfly/flyctl-actions/setup-flyctl@master
#
#      - name: Build Frontend (Staging)
#        run: npm run build:staging
#
#      - name: Deploy to Staging with Fly
#        env:
#          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#        run: |
#          flyctl auth token $FLY_API_TOKEN
#          flyctl deploy -a $APP_NAME
#
#      - name: Run Blackbox Tests (Staging)
#        run: npm run test:staging
#
#      - name: Run e2e Tests (Staging)
#        run: npm run e2e:staging
