name: Staging Behavioral Test

on:
    schedule:
      - cron: '0 1 * * *' # Run daily at 3 AM
    workflow_dispatch: # Manual trigger

jobs:
  staging-behavioral-test:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'web-app-template'
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      PB_ADMIN_PASSWORD: ${{ secrets.PB_ADMIN_PASSWORD }}
      PB_ADMIN_EMAIL: ${{ secrets.PB_ADMIN_EMAIL }}
      STAGING_PB_ADMIN_PASSWORD: ${{ secrets.STAGING_PB_ADMIN_PASSWORD }}
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Install dependencies
#        # runs "npm i" as well
#        uses: cypress-io/github-action@v5
#        with:
#          runTests: false

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run blackbox tests
        working-directory: ./backend
        run: npm run test:staging

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install playwright
        working-directory: ./frontend
        run: npx playwright install

      - name: Run e2e tests
        working-directory: ./frontend
        run: npm run test:staging